Replace str() by unicode() (#17)
* Replace str() by unicode()

This fixes the following bug: If the user entered a non-ASCII character
into one of the filter text boxes (for example, by hitting the 'u umlaut' key on a
German keyboard), the application crashed before with the following
error:

    Traceback (most recent call last):
      File "/home/martin/ros/kinetic/rqt_graph/src/rqt_graph/src/rqt_graph/ros_graph.py", line 69, in splitPath
        path = str(path.split(',')[-1]).lstrip(' ')
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 16: ordinal not in range(128)

This commit fixes that.

* Check for missing unicode() function (py3)